### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/draft-guide-kubernetes#11]
Very good guide.

Some minor changes needed.

- [x] `visit the official IBM chart GitHub repository` --> points to 
https://github.ibm.com/IBMPrivateCloud/charts/tree/master/stable/ibm-open-liberty
Instead point to public repo : https://github.com/IBM/charts/tree/master/stable/ibm-open-liberty

- [x] `See the official Open Liberty Helm chart GitHub repository for more `
Same issue as above.

The unreleased Open Liberty Helm Chart version 1.5 contains the fix for using new NGINX annotations and some of the parameters have changed. The guide needs be updated accordingly.

- [x] `secureBackends` (under `ingress`) was removed - the logic is now controlled by `ssl.enabled`.
- [x] `service` now has `enabled` argument - default value is `true`

**Comment by leochr** [comment]
@Kubik42 @evelinec 

Hi, 

Open Liberty Helm chart v1.5.0 is now released and available in the IBM's public helm repo: 
https://github.com/IBM/charts/tree/master/stable/ibm-open-liberty

It includes the NGINX annotation fix. So the temporary instructions from this section can now be removed I guess:
https://github.com/OpenLiberty/draft-guide-kubernetes#installing-a-helm-chart-release

**Comment by Kubik42** [comment]
Thanks @leochr ! I'll start cleaning those up

**Comment by Kubik42** [comment]
@leochr addressed in 37d0d91e3a8508e5d31d9571f434487a4e248f33. Feel free to close if there is nothing else. 

Thanks again for your feedback!
