### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by wojtczat** [OpenLiberty/draft-guide-kubernetes#19]
I could not get minikube running on Windows, so I completed the guide on my Ubuntu VM. Once I made it through the setup portion of the guide, I actually had a pleasant experience. For the most part each command executed smoothly and had a suitable amount of documentation to provide myself with an adequate knowledge of the concepts to continue moving forward. 
Here are a few suggestions that I believe would have improved my experience:

1. I would consider changing the last sentence of the second paragraph in the "What You'll Learn" section where you begin mentioning pods. Even though this is only quickly mentioned, I think people would maybe still need a background on pods to understand your statement. To fix that, I think you could just put the "What is Kubernetes?" section first as I do not believe that would be a bad starting point either. 
2. The setup is obviously a tedious process with minikube so if there are better resources to quickly get through this process I would try my best to include them. The quickest way I was able to have a working version of minikube was by followig the commands in Navid's Kubernetes' lab for Ubuntu. Here is the link (https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/Wfe97e7c353a2_4510_8471_7148220c0bec/page/Kubernetes%20Education)
3. If the minikube commands on windows require extra flags they should be provided for the user instead of having them hunt them down themselves. 
4. When running `mvn verify` for the tests I originally had some failures and errors. I was uncertain why, but eventually they worked. Maybe just review this section to ensure everything is okay because I am pretty sure I never introduced a bug into the code.  
5. Excluding the setup and including the optional section I think completing the guide did take over 30 minutes so I would review that and make sure it is accurate.

**Comment by evelinec** [comment]
@Kubik42 is this being addressed where possible for the guide and the rest in the setup instruction?

**Comment by evelinec** [comment]
@wojtczat can you review the changes and see if they address all of the issues you raised, except for the setup instruction. That'll be covered separately. Thank you.

**Comment by wojtczat** [comment]
Yes, this all looks good now.
