### ISSUE TITLE
Present platform-specific commands appropriately

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-kubernetes#27]
With the use of Docker for Windows and Docker for Mac that come with Kubernetes for Windows and Mac respectively, we will need to cover different commands for different platforms.  (Kube is a separate install for Linux.)

We need to work out the best possible way to present this within what we have today, update the (draft) guide accordingly, and take it up for review and feedback.

Should clean up the guide where appropriately given these latest considerations too.

**Comment by proubatsis** [comment]
I laid out my ideas for how to solve this issue in #29 , let me know what you think.

**Comment by yeekangc** [comment]
Tagging @cajaygle @megmulsy @lauracowen if they have thoughts.  @kinueng @mbroz2 @gcharters @NottyCode, FYI and your feedback welcome too.

The team will work out options given what we have and share them ASAP.

**Comment by kinueng** [comment]
I think https://github.com/OpenLiberty/draft-guide-kubernetes/pull/29#issuecomment-419937079 is suggesting we have a single code block with selectable tabs on top.  The tabs would be labeled as "Windows, Unix, ..." and a reader can click one of the tabs to show the platform specific command.

If we want a code block with tabs, we will need to write an Asciidoc extension to support tabs since Asciidoc does not have native tabs support.

**Comment by yeekangc** [comment]
@kinueng, that is an idea or an option.  We don't have a decision on that yet but I will suggest for @cajaygle and @megmulsy to consider what will be the appropriate design for this using the Kube and Istio guides as the basis.

In the mean time, we are moving forward to try to wrap the Kube and Istio guides with what we have today -- with Asciidoc as-is; granted they must be consumable -- and any visual or design improvements can come later (as part of multi-pane layout).

**Comment by cajaygle** [comment]
I also feel that having a single box with the platform-appropriate command would be the best.  we can auto-detect their platform, and at the beginning of the guide or first appearance of a platform-specific command we tell them we've auto-detected their platform and give them the option to change it.  then all subsequent instructions would use that platform to display the appropriate command.   if we did that then maybe we wouldn't need a selection mechanism for each command block, or that may still be useful to include on each.

**Comment by proubatsis** [comment]
One thing to keep in mind is that it may not be **only** the commands that change. You may want a slightly different instructions as well. For example, in this guide we need to run `minikube start` for one platform, and for another platform we tell them to go to their settings and check a box. We could probably write them in a way such that only the commands change, but it would be more flexible to take into account that some instructions may change as well.

**Comment by evelinec** [comment]
I think we're done with this issue with the current guide(s).
