### ISSUE TITLE
User Review on Windows Machine

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/draft-guide-kubernetes#31]
### Timing
Kubernetes Guide without optional section: ~ 55 minutes
Optional section (alone): ~ 15 minutes

### Overall Feedback:
After reading the Windows/Mac version and I see a Linux step, I feel the need to read through the Linux step to make sure I didn't miss anything else that was meant for the Windows/Mac version. There were also times when I ran the Linux command instead of the Windows/Mac. 
- [x] Perhaps we could have two separate guides or links for Windows/Mac and Linux instead of putting them together. 

The user also only edits the code one time to change the greeting message in `NameResource.java`. Otherwise, the `start` and `finish` directory are identical. 
- [ ] Is it necessary to have a start/finish structure for this guide?

Who is the audience of this guide? Are all sections necessary for this audience? 
- [x] This guide is quite long so maybe it is worth thinking about splitting it up into parts.

The prerequisites took a bit of time to complete and involved navigating to several external websites
- [ ] It may be worthwhile to create our own set of pre requisites on the OL site

### Specific Feedback:
**Starting and preparing your cluster for deployment**
>$ kubectl get pods --all-namespaces 
- [x] There is an extra '$' that was probably copied by accident that should be removed

**Installing a Helm chart release**
>`helm install --name ol-name --set image.pullPolicy=IfNotPresent --set image.repository=name --set image.tag=1.0-SNAPSHOT --set ssl.enabled=false --set service.port=9080 --set service.targetPort=9080 --set ingress.enabled=true --set ingress.rewriteTarget=/api/name --set ingress.path=/name ibm-charts/ibm-open-liberty`
and
>`helm install --name ol-ping --set image.pullPolicy=IfNotPresent --set image.repository=ping --set image.tag=1.0-SNAPSHOT --set ssl.enabled=false --set service.port=9080 --set service.targetPort=9080 --set ingress.enabled=true --set ingress.rewriteTarget=/api/ping --set ingress.path=/ping ibm-charts/ibm-open-liberty`
- [ ] This command does not work properly in `git bash`, this may be worth noting if users are using `git bash` 

**Scaling a deployment**
- [ ] It may be helpful to give users an example of how to create a unique session vs. non-unique session (ex. to open an incognito window)

**Testing micro services that are running on Kubernetes**
- [x] Should include a line that tells user they need to navigate 
- [x] It felt especially unclear which `mvn verify` command to run because when there were separate instructions for which machine you were working with previously, it showed `Windows/Mac` and `Linux`, also the ordering is different from the rest of the guide which usually showed Windows/Mac instructions BEFORE Linux instructions

**Tearing down chart releases**
- [x] This section should be included after the Optional portion of the guide OR there should be a disclaimer to not tear anything down if you want to try the optional section

**Optional: Editing Kubernetes resources using Minikube**
- [ ] The title is misleading since you can use the Kubernetes dashboard directly to edit the kubernetes resources 
- [ ] The instructions to access the ingress resource through the dashboard UI could be more clear (ex. "Click on Ingresses under Discovery and Load Balancing")

**Comment by evelinec** [comment]
Regarding "create our own set of pre requisites on the OL site", I think it's referring to the setup instructions. That will come as part of the kube guide. The start and finish folders are the structures of the guides. The rest of the points are not relevant in the revised guide anymore.
