### ISSUE TITLE
User Feedback the Kubernetes guide for MAC user

### ISSUE THREAD

**Issue by Rachelwrq** [OpenLiberty/draft-guide-kubernetes#32]
### Timing
**Without the optional part**: 40 minutes
`mvn package` and `mvn verify` took up more than 5 minutes in the process

**Optional part alone**: 10 minutes

### General Feedback
The guide took relatively long compare to other open liberty guide, but it is very informative in terms of covering different major aspects of Kubernetes. Compare my past experience with other Kubernetes tutorials and online courses, this guide did cover the similar topics with the addition of explaining more about ingress; but enabling the ingress allows audience to see the product so it is a good thing to have. 

#### What you will Learn
- [ ] the sentence "making it easy to distinguish it from its other replicas:” might need rephrasing

#### Starting and preparing your cluster for deployment
- [x] one of the command: `kubectl get pods —all-namespaces` cannot get copied, does not line up with other command well

#### Scaling a deployment
- [ ] "Wait until 2 pods are ready": maybe mention again how to check for user's convenience

- [ ]  Audience might need more clarification about the difference in **unique** and **non-unique** sessions
#### Rolling out Deployment updates
- [x] After navigate to the name directory, user just stayed there for the rest of the guide. Just wondering if this is a normal thing to do or should user navigate back to the start directory.

#### Testing microservices that are running on Kubernetes
- [x] There are 3 cases with corresponding instructions to run; but the way the instructions are presented made it confusing to audience. Audience might think it's three sequential steps, this situation can be solved by choosing a different kind of markdown.

#### Optional: Editing Kubernetes resources using Minikube
- [ ] The title is somewhat misleading because the instruction underneath says that one can use editing without minikube.

- [ ] The position of this part is very awkward. It would make more sense to place it before "Tearing down the chart releases"; so user still have access to the application that they installed.

- [ ]  the third paragraph is not as instructive as the rest of the guide, an actual example that works with this guide would be helpful to add along side this generic expression `kubectl edit (RESOURCE/NAME | -f FILENAME) [options]`

**Comment by evelinec** [comment]
The rest of the feedback aren't relevant in the revised guide anymore.
