### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-kubernetes#35]
My `kubectl` installation (brew on Mac) failed (error at the end of this issue) so I couldn't test it, just read it through.

Comments as I was reading:

- [x] ‘a developer’s primary tool’ - not really - it’s a devops tool, isn’t it? While a development scrum might be responsible for end-to-end story, I think it’s a push to say ‘developer’. Maybe just say 'a primary tool for deployment'....etc

- [x] seems very long for a guide…too many optional bits. This isn’t meant to be a comprehensive piece of doc. Remove the optional minikube section at the end. It’s good to point them to do something next (I like that) but it’s too long. I think that ‘editing Kubernetes resources using Minikube’ should be (if required) a separate Docs topics that the guide links to. In general, I think there needs to be a clear scope for what the guide is trying to achieve (what the user is to learn from it). If it's too long, they'll not learn it anyway.

- [x] Don’t offer options (“and while you’re not limited to any of them in particular, you should use Docker”). Sure, say there is support for several but instruct them to install Docker.

- [x] Don’t say ‘recommended’ - who’s recommending it? It’s not clear. If you want them to install it, just tell them to install it. Don’t hedge - it just leaves the reader unsure about what they have to do.

- [x] I don’t understand the relevance of the whole paragraph starting: ‘Docker Desktop is a convenient way’ - does Docker Desktop replace the steps above? If so, why are we giving them both sets of instructions? Be dictatorial. Just tell them what to do for the best experience, ie tell them to install Docker Desktop on Mac/Windows and Minikube on Linux, then tell them any additional steps for kubectl etc. Don't make them have to work it out or guess. It seems that with Docker Desktop installed (Mac), I don’t need to install kubernetes? But I do seem to need to install kubectl. Didn't get any further.

- [x] 	“If you’re familiar with Maven and Docker, you might be tempted to run a Maven build first and then use the .war file produced by the build to build a Docker image. While this is by no means a wrong approach, ” - just tell them what to do in this scenario. Don’t tell them the alternatives here. eg start the paragraph from “you can build your microservices and Docker image simultaneously …”. Also, is it really ‘simultaneously’? Or just as part of the same build?

- [x] 	“If the build is successful” - why wouldn’t it be successful? Is it likely to go wrong? Why? If not, just say “when the build has completed, run…”

- [x] Style  - don’t highlight or capitalise the terms (eg pod, node, controller, etc). It’s distracting and unnecessary. The name of actual resources (eg name and ping) if they don’t stand out from the sentence in any other way is fine to highlight. Service, Pods, etc should all be lower-case - don’t capitalise nouns for the sake of it.

- [x] 'statefulsets’ and ‘daemonsets’ - if you’re not going to define them, don’t mention them - it’s just confusing/distracting because I'm now wondering why you told me and what I'm to do with that information.

- [x] present tense for how a technology works eg ‘In a basic scenario, a Kubernetes service exposes a node port…’

- [x] ‘as well as provides load-balancing ’ - grammar needs fixing; probably sentence needs to be shorter so it’s easier to match the grammar.

- [x] ’Starting and preparing cluster’ section - missing a Windows/Mac heading somewhere towards the end of the section.

- [x] Table of parameters should have the qualifier listed in each row for clarity. Actually, I don’t think the table is that useful as you have to go back and forth to understand what it’s telling you. Just describe the key parts of one of the commands. Not all parameters need describing, probably? Link to a reference topic of all the parameters so someone really interested can go find out. The purpose of hte guide is not comprehensive documentation but to explain why the app does what it does and what it achieves. The table is not ‘breaking it down’ - it’s just presenting the reader with a bunch of information that they have to link together.

- [x] Present tense for describing how the technology works. eg ‘The first URL returns a brief greeting…’ “You can see a brief message”, “…no special messages are displayed” etc

- [x] What’s an “apiserver”? (not a real word...check this whole paragraph to make sure it makes sense)

```
==> Downloading https://homebrew.bintray.com/bottles/kubernetes-cli-1.11.3.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/e1/e1859f9f893237aa977be328846481b362e147ae92c2cde3e65a7d445b02dae9?__gda__=exp=1537366208~hmac=7a9f9feff6d49dab962f0082cc5dc5a19128de382c663482d00cb66553274ae9&response-content-disp
######################################################################## 100.0%
Error: No such file or directory @ dir_chdir - /usr/local/Cellar
Warning: Bottle installation failed: building from source.
==> Installing dependencies for kubernetes-cli: go
==> Installing kubernetes-cli dependency: go
==> Downloading https://homebrew.bintray.com/bottles/go-1.11.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d2/d2dfd9846bc03498dd69c01eaccc0a3018a66d00864d7433d70f07645aac6a40?__gda__=exp=1537366210~hmac=bd93f2bfa882de1a92b2cdae54f154499c87fdd23249a097d25125cc1532f3ca&response-content-disp
######################################################################## 100.0%
Error: No such file or directory @ dir_chdir - /usr/local/Cellar
Warning: Bottle installation failed: building from source.
==> Downloading https://dl.google.com/go/go1.11.src.tar.gz
######################################################################## 100.0%
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:572:in `install_dependency'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:534:in `block in install_dependencies'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:534:in `each'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:534:in `install_dependencies'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:394:in `compute_and_install_dependencies'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:300:in `rescue in install'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:287:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: An exception occured within a build process:
  Errno::EPERM: Operation not permitted @ dir_s_mkdir - /usr/local/Cellar
```

**Comment by evelinec** [comment]
Assign to @proubatsis to see if the remaining feedback is still valid on the revised guide.

**Comment by proubatsis** [comment]
PR Merged. Closing Issue. Due to the re-write, some of the feedback was no longer applicable.
