### ISSUE TITLE
Few minor things on 9/21's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-kubernetes#38]
Tested the latest guide on Mac and everything is working. Few minor things that need to be addressed: 

- [x] The `start/` directory to be specified as `start`

- [ ] The `curl` command didn't work: 
```
curl http:localhost:31000/api/name
curl: (3) Port number ended with 'l'
```

- [x] The guide's duration can be 20-30 minutes now

**Comment by proubatsis** [comment]
> The curl command didn't work:
@evelinec That error is because the URL should be `http://localhost:31000/api/name` and not `http:localhost:31000/api/name`

**Comment by proubatsis** [comment]
#42

**Comment by evelinec** [comment]
Oops, I thought I copied and pasted the curl sample line and just modified the hostname. Thanks!
