### ISSUE TITLE
User Feedback (Windows)

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/draft-guide-kubernetes#39]
The new guide (without Ingess', helm and optional section) is a lot more manageable in the allocated time. Overall everything was easy to setup (Docker for Windows) and I didn't run into any issues. 

Although, the entire guide still took me roughly 50 minutes (not counting pre-requisites). This is largely due to the fact that the first `mvn package` command took ~19 minutes. 

### General

- [x] `Pods` is in backticks towards the start of the guide, but isn't towards the end. Should be consistent and either use `Pods` or Pods.

### Prerequisites
- [x] When selecting `Enable Kubernetes` in Docker, there are two sub-options: Kubernetes and Swarm (default). Might be good to specify which one to select.

###  Building and containerizing the microservices
- [x] First `mvn package` takes a long time (~19 minutes)
- [x] "If the build is successful" -> Should write with certainty, maybe: "When the build is successful" 
- [x] `Quay.io/kubernetes-ingress-controller/nginx-ingress-controller` not present after running `docker images` even though build was successful

### Deploying the applications
- [x] A Kubernetes Deployment is a resource**s** responsible for -> typo
- [x] Run the following commands to deploy the resources as **define** in kubernetes.yaml -> typo

### Scaling a deployment 
- [x]   Scaling is one of the primary advantages of Kubernetes because it allows to accommodate more traffic, -> "because it allows to accommodate traffic" sounds awkward, consider re-wording 
- [x] and descale **them** to free up resources when the traffic decreases. -> can be ambiguous, de-scale what?

### Testing microservices that are running on Kubernetes
- [x] To run the tests, wait for all Pods to be in the ready state, then run the `mvn verify` command. -> This part is confusing, should the user be running `mvn verify` right now? Or is this referring to the mvn verify command that comes up later in this section?

### Great work! You're done!
- [x] You then scaled a microservice, ran integration tests against miroservices that are running in a Kubernetes cluster. -> You then scaled a microservice **and** ran integration tests against miroservices that are running in a Kubernetes cluster.

**Comment by proubatsis** [comment]
#40

**Comment by proubatsis** [comment]
@andrewdes The PR has been merge, if all looks good then please close the issue.
