### ISSUE TITLE
Unused import in NameEndpointTest and PingEndpointTest

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-kubernetes#43]
Following import not necessary in NameEndpointTest and PingEndpointTest

import java.security.NoSuchAlgorithmException;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.security.cert.X509Certificate;
import java.security.cert.X509Certificate;```

**Comment by proubatsis** [comment]
@gkwan-ibm Pull request open: #44

**Comment by proubatsis** [comment]
PR Merged
