### ISSUE TITLE
SME review feedback on 9/27's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-kubernetes#46]
Just went through the Kubernetes guide. Excellent guide to get started with Kubernetes! I like the fact that the key terms and concepts of Kubernetes are explained well without overwhelming new users.
 
Minor suggestions:
 
1) Perhaps the following sentences could be reworded (sorry, not a fan of words 'whatever' and 'thing')
 
"Finally, the container port containerPort is whatever the port that your container exposes for purposes of accessing your application. For the services the main thing key point to understand is that"

 
2) Some users may misinterpret the following statement about NodePort differently - that it's accessible within the cluster only. It may be worth to clarify/mention that the services would be accessible even from outside the cluster on Node’s IP at the specified port.
 
"You will also notice that the service has a type of NodePort. This means that you will be able to access these services in your cluster via a specific port."

**Comment by proubatsis** [comment]
Addressed in #45

**Comment by proubatsis** [comment]
PR Merged
