### ISSUE TITLE
ID critique overview edits

### ISSUE THREAD

**Issue by sishida** [OpenLiberty/draft-guide-kubernetes#5]
General notes:
- [x] Introductory phrases/clauses should be set off by commas.
- [x] If a sentence has a subject and a verb/a complete clause on either side of the conjunction, the conjunction requires a comma after it. Example: "Stacy bought and used a laptop throughout college." (no comma) but "Stacy bought a laptop for college, but she uses a desktop at home." (comma included)
- [x] Try to avoid parenthesis and quotation marks unless they are part of the code itself.
_removed all instances of parenthesis and quotations marks that were unecessary_
- [x] Avoid first person pronouns like "our" and "we."
_removed all instances of "our", there were no instances of "we"_
- [x] Avoid using "this" as a standalone noun. Specify what "this" is, such as "this microservice."
- [x] Use "want" instead of "wish."
_replaced one instance of "wish" with "want"_
- [x] Unless the acronym is very common, such as URL, spell it out in the first instance where it is used. For example, say "GitHub Enterprise (GHE)" the first time. Subsequent instances can then just be the acronym by itself, "GHE."
- [x] An apostrophe plus "s" doesn't just indicate possessives but can also be a contraction for a word plus "is." For example, "that's" equals "that is."
- [x] Use "once" to indicate "one time." Words like "when" or "after" can be substitutes for "once" if you don't intend to mean "one time."
_replaced all such instances of "once" with "when"_
- [x] Try to avoid "should." I understand that the possibility always exists that something might not work. However, it's OK to say a statement that sounds more definitive, such as, "After you do x, the server runs." instead of, "After you do x, the server should run."
- [x] Avoid "etc." and use "and so on" instead.
- [x] Keep to the present tense. I notice future tense creeps in here and there in this guide. It's OK to use future tense a little bit, but aim to make over 90% of the sentences present tense.
- [ ] Oftentimes it's good to remove adverbs, such as "really" and other descriptive "-ly" words. I understand that these words can contribute to a more casual tone, but even in fiction writing, adverbs are discouraged because a stronger noun or verb is preferable. Example: Using the word "famished" is preferable to saying "very hungry."
_By descriptive "-ly" words, do you mean ones like "really", "very", "extremely", etc. or all "-ly" words like "automatically", "manually"?_
- [x] If "as" can be interchanged with "because," I think "because" is a little more clear.
_changes all "as" instances to a mix of "because" and "since"_
- [x] Make sure it's clear what a pronoun refers to.
- [x] A couple of headings indicate "Alternative." It would be nice if we could connect the alternative step to what it's an alternative to in a way that's more clear.
_I'm definitely going to rework the guide a little bit and remove those "alternative" sections_
- [x] On a related note, this guide felt long, and I felt myself losing track of how everything connected. What if we omitted some parts? Sure, you might be able to do certain things more than one way, but do we really need to tell the user the different options to get started? Sometimes when I'm building something, I like to just follow the steps to put it together and not have to choose different options. :)
_Yes... it is quite long, I can probably omit all the alternate routes and just have the users follow through the steps strictly. Some of the optional stuff can probably be moved to a more advanced topic on kubernetes_
- [x] Check out the IBM word usage list to learn about how certain words or phrases should be spelled, such as whether "set up" should have a hyphen or not: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/W580a84a67242_4da6_81cf_69e3db4bdbfa/page/Word%20usage This list is a good resource that you might want to bookmark. :)
_doesn't seem like I have access to that link :(. I changed all instances of "setup" and "addon" to "set-up" and "add-on"_

Short description
- [x] When you use a pronoun, make sure that readers understand which noun it refers back to. "Them" might be a little unclear here. Do we have to mention "Helm charts"? I'd say omit that mention if we can.
_Yes, good point. It'll probably make the guide more searchable as well. Removed_
- [x] Also, when you have a name, variable, or the like, put the name before explaining what it is. For example, put "kubectl" before "Kubernetes CLI".
- [x] Suggested changes: "Explore how to deploy microservices to Kubernetes and manage them with the kubectl Kubernetes CLI."
_Should have read this point first :P This is exactly what I ended up with after making the two changes above_

What you'll learn
- [x] Place punctuation within parenthesis.
- [x] However, in the case of the parenthesis around "charts," I would simply omit the parenthesis.
- [x] Put a descriptor word after something in a code phrase, such as, "The `kubectl` interface is your primary tool..."
- [x] Missing period at end of the last sentence of the first paragraph.
- [x] Directional words (like "under" in the second paragraph) are potentially confusing for visually impaired users who get help from screen readers. Could we say "within" or some alternative instead?
_Replaced "under" with "in" when speaking about directories_
- [x] Avoid using "this" as a standalone word. Either add a noun after, such as "This display," or attach it to the other sentence if it won't make the sentence too long, such as "...runs in, which makes..."
_This is what I ended up with: "The `name` microservice simply displays a brief greeting and the name of the container that it runs in, making it easy to distinguish it from its other replicas. The `ping` microservice simply pings the {kube} Service that encapsulates the Pods running the `name` microservice, demonstrating how communication can be established between Pods inside a cluster."_
- [x] "its" is the possessive form of "it." In "its been replicated," you want "it's" because the apostrophe indicates "it is." Also consider rewriting to avoid the pronoun altogether, such as, "...running instance of the microservice from another after the microservice is replicated..."
- [x] Remove the quotation marks from "pings."
- [x] "add-on" has a hyphen.

What is Kubernetes?
- [x] "open source" is not hyphenated.
- [ ] What about something like..."Kubernetes is a major tool in containerized environments. Containers can be useful in all steps of a continuous delivery pipeline."
_Maybe "Over the years, Kubernetes has become a major tool in containerized environments as containers are being more and more utilized for all steps of a continuous delivery pipeline."?_

Architecture
- [x] Try to avoid the use of first person "we" here. Instead, write something like, "Deploying an application to Kubernetes means deploying an application to a Kubernetes cluster."
- [x] Make sure capitalization is correct. It appears to me that "nodes" is lower case, but "Pods" is upper case. I will defer to the developers' decision on whichever is correct, but please make it consistent.
_I just kept everything capitalized. Kubernetes didn't seem very consistent with their capitalization in their own documentation. It seems through that nodes is usually not capitalized though, so I changed "Nodes" to lowercase._
- [x] Adverbs that end in "ly" generally do not need to be hyphenated because it's clear that they're adverbs. For example, "closely coupled" does not need a hyphen.
- [x] Use a comma plus "which" to introduce a nonrestrictive clause. Use "that" to indicate a restrictive clause. Example: "It represents a single running process **that** encapsulates a container or in some scenarios multiple closely coupled containers."
- [x] Try to keep words like "However" at the beginning of sentences. If you do use them in the middle, set off the word with commas on either side, such as, "With Open Liberty, however, you can..." Set off other nonessential words like "Of course" with commas, too.
- [x] You don't need a comma after "cluster" in the last sentence of this section. I'm assuming that you want to say that the Kubernetes object maps external requests to the Services inside a cluster and [the Kubernetes object] provides additional functionality.
_yep :)_
- [ ] An illustration/diagram might help show how the different parts of Kubernetes are related.
_I originally had this, but YK was against it. I'll bring it up to him again though._

Why use Kubernetes?
- [x] I'm thinking we want this section earlier in the doc so that the user will be motivated to learn more about Kubernetes. At least put it above the "Architecture" section. Consider moving some of the info under "What you'll learn" down to the "What is Kubernetes?" section so the reader sees the "Why use Kubernetes" info that much earlier.
- [x] typo: "experience developers" should be "experienced developers"
- [x] Info on "24/7" from the IBM word usage guide: "Do not use this abbreviation to indicate high availability, nonstop operation or support, such as for database and e-commerce applications or monitoring. Do not use to indicate the general availability of something, such as service. If you must use an abbreviation, use "24x7" instead. "24x7" is acceptable usage, provided that you are consistent within a document or library. However, if possible, use descriptive wording instead.
Whenever possible, use descriptive wording, for example, "High-availability databases not only are universally available but also have high reliability and serviceability" or "Operations are monitored 24 hours a day, every day of the week.""
_Replaced with "...and all needing to be run and monitored every day of the week will give..._
- [ ] Try to avoid "there" as a subject of a clause.
_Not sure I understand this part. If I split that sentence into two will it be ok?: "Of course this is just a simple example. There is much more underneath the iceberg that is Kubernetes"_

Prerequisites
- [x] The hyphen or dash after each tool sort of resembles a minus sign. The best solution might be to make the bullet points complete sentences. For example, "The `kubernetes-cli` tool is..."
- [x] Prepositional phrases like "For installation instructions" should be set off with a comma at the beginning of a sentence.
- [x] Even if a sentence ends with a hyperlink, it should also end with a period. Just make sure that the period is not included as part of the hyperlink. :)
- [ ] Set off nonessential clauses (like "while you're not limited...") with commas.
_So, it would be like this:? "Kubernetes supports a variety of container types and, while you're not limited to any of them in particular, you should use Docker..."_

Starting and preparing your cluster for deployment
- [x] Unless it's the first word of the title or a word that's always capitalized like a name, the words in a title should be lower case. I see "deployment" as both lower case and upper case in this file.
- [x] I'd remove the word "Note." 
- [x] typo: "you cluster" should be "your cluster"
- [x] "add-on" should be hyphenated.
- [ ] I noticed "Ingress" and "Pod" were formatted as code earlier, but here they are not. I'd prefer that we consistently format them the same way. 
_I formatted them as code at the start to make them stand out more. I don't think they need to be formatted like that throughout the rest of the guide._
- [x] "frontend" should be "front end" (noun) or "front-end" (adjective).

Installing a Helm chart release
- [x] "Temporary instructions" sound kind of strange. How long will they be temporary? If possible, maybe specify a version number that they apply to?
_They'll be gone when the guide is published. There is currently some additional steps that need to be done, which another team is working on adding permenantly to their Helm chart._
- [x] typo: "resource each" should be "resources each"
- [x] "quite" can have different meanings. I would remove it altogether.
- [x] I assume that "Kubelet" in the table is a typo.
_Its actually just the name of a service that Kubernetes uses. I suppose I can change it to Kubernetes though just to avoid confusion._
- [x] Correct the "to to" and "it will used" typos.
- [x] Info about "via" from the word usage page: "Use this term, which means "by way of," to refer to routing data, such as in "Messages are routed via SMTP." In other situations, try to replace "via" with one of the following synonyms: "across," along," "by," "from," "on," or "through.""
_Replaced "via the Ingress" with "from the Ingress"_

Scaling a deployment
- [x] Typo? "multiple session...you also saw how your Ingress controller persists session."
_Yep! Good catch. It should be plural._
- [x] Put a word in code phrase format if it's something the user has to enter/specify, such as setting the parameter to "true."

Rolling out Deployment updates
- [x] typo: "withing" should be "within"

Automating with Maven
- [x] Use "an" before "update-deployment profile." "A" or "an" is determined by the word that follows directly after it. "A" is for words that begin with consonants; "An" is for words that begin with vowels.

Testing microservices that are running on Kubernetes
- [x] typo: "you can use set"

**Comment by Kubik42** [comment]
The checked stuff is in as of f0023125a25580e443b6e5be87098926ffe7a807

**Comment by sishida** [comment]
Answers to questions:
- Ah, I could have clarified this a bit better! The descriptive "-ly" words that we want to remove are the ones that don't add much value, such as "really", "very", "extremely", etc. The "-ly" words like "automatically", "manually" can be useful and can be included.
- "Setup" should actually be spelled as shown here, as one word and without the hyphen. I'm also not sure why you can't access the link to the word usage list, but it's OK if you can't. You can use TermBot on Sametime (http://tlwi.w3-969.ibm.com/standards/terminology/Termbot.html) instead if you're ever curious about the terms. :)
- If we don't want a diagram to show the different parts, maybe we could use a table or a list to help visually separate the parts as explained by the text?
- As for the issue with "there," the word "there" just doesn't add much or convey much when it's used as the subject of the sentence. Maybe we could change "There is much more underneath the iceberg that is Kubernetes." to something like, "The iceberg of Kubernetes has much more underneath."
- Yes, you used the commas correctly in "Kubernetes supports a variety of container types and, while you're not limited to any of them in particular, you should use Docker..." A good indicator that something is nonessential (and thus needs the commas) is to read the sentence without that part. For example, it is sounds OK to say, "Kubernetes supports a variety of container types, and you should use Docker..."
- I'll look at the Ingress and Pod formatting when I do the line edits. I can see why we'd like to make them stand out early on, but I also think consistency can be useful. For example, I wouldn't want to confuse the readers into thinking that Pod with the code phrase is somehow different than the Pod without the code phrase format.

**Comment by Kubik42** [comment]
- thanks for the clarification :)
- changed all "set-up" instances to "setup"
- @yeekangc what do you think about a diagram for this guide? I added a sample diagram I put together below
- Changed the sentence to " the iceberg that is {kube} has a lot more to offer."
- removed the comma to now say "supports a variety of container types and while you're not limited to any of them in particular, you should use Docker..."

![setup](https://user-images.githubusercontent.com/11563877/44103243-b340be5a-9fb9-11e8-8f97-8cb4c0d205b3.png)

**Comment by yeekangc** [comment]
@gkwan-ibm, can you please take a look?

**Comment by yeekangc** [comment]
@proubatsis, can you please follow up and wrap these up too?

**Comment by proubatsis** [comment]
Several sections have been removed and/or significantly changed and the guide will go through ID review again.
